### PR TITLE
feat: startup scripts to MWAA resource

### PR DESCRIPTION
**Pull request by barrysteyn**
The ability to pass `startup_script_s3_path` and `startup_script_s3_object_version` to underlying MWAA terraform resource.

### CODE REVIEW

**Comment by barrysteyn** [comment]
@mgerlach @jdiebold Could you guys look into please merging this? Also, the generate docs seems to be failing because it can't access my forked repo. I think that could be an error in that GH action.

**Comment by barrysteyn** [comment]
@mgerlach That should be fine. Thank you so much for the quick response.

**Comment by mgerlach** [comment]
@barrysteyn Could you try to recreate the PR again, but this time against the fork_prs branch of the idealo repo? You might have to fork again, including all branches.

Idea is that we can then create a PR from fork_pr against main, preserving your commits with you as author, but enabling the generate docs action to modify that new PR created by us.

**Comment by barrysteyn** [comment]
Sure thing... I will do this now....

**Comment by barrysteyn** [comment]
Done!

**Review by mgerlach — APPROVED** [review]

**Comment by mgerlach** [comment]
Released by #120

**Pull request merged**
